name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8 AM UTC 

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit App
        run: curl -s https://cardiodiff-vae.streamlit.app/
