[[pages]]
path = "0_Home.py"
name = "Home"

[[pages]]
path = "1_Latent_Space.py"
name = "Genome Navigator"
icon = ":material/scatter_plot:"

[[pages]]
path = "2_Clusters_Navigator.py"
name = "Cluster Navigator"
icon = ":material/explore:"

[[pages]]
path = "3_Ontology_Navigator.py"
name = "Ontology Navigator"
icon = ":material/menu_book:"

[[pages]]
path = "4_Data.py"
name = "Data Navigator"
icon = ":material/table_rows:"

[[pages]]
path = "5_Help.py"
name = "Help"



[[pages]]
path = "6_About.py"
name = "About"
