[[pages]]
path = "0_Home.py"
name = "Home"

[[pages]]
path = "1_Clusters_Navigator.py"
name = "Cluster Navigator"
icon = ":material/explore:"

[[pages]]
path = "2_Latent_Space.py"
name = "Genome Navigator"
icon = ":material/scatter_plot:"

[[pages]]
path = "3_Data.py"
name = "Data Navigator"
icon = ":material/table_rows:"

[[pages]]
path = "4_Help.py"
name = "Help"



[[pages]]
path = "5_About.py"
name = "About"
