[[pages]]
path = "0_Home.py"
name = "Home"



[[pages]]
path = "1_Latent_Space.py"
name = "Gene search"
icon = ":material/scatter_plot:"

[[pages]]
path = "2_Ontology_Navigator.py"
name = "Term search"
icon = ":material/menu_book:"

[[pages]]
path = "3_Clusters_Navigator.py"
name = "Clusters"
icon = ":material/explore:"


[[pages]]
path = "4_Data.py"
name = "Data"
icon = ":material/table_rows:"

[[pages]]
path = "5_Help.py"
name = "Help"



[[pages]]
path = "6_About.py"
name = "About"
